### ISSUE TITLE
Doesn't build yet - NOTES

### ISSUE THREAD

**Issue by z3ntu** [z3ntu/cyanogenmod_fp_FP1#1]
Some notes here

**Comment by z3ntu** [comment]
`~/android/system/kernel/fp/FP1/mediatek/platform/mt6589/kernel/Kconfig/Drivers`
Line 240
`bool`

**Comment by z3ntu** [comment]
`find: '/home/luca/android/system/kernel/fp/FP1/kernel/../mediatek/config/cm_FP1': No such file or directory`

**Comment by z3ntu** [comment]
Comment #2 with `def_bool y` (http://lists.infradead.org/pipermail/barebox/2013-November/017013.html)

**Comment by z3ntu** [comment]
```
/home/luca/android/system/kernel/fp/FP1/kernel/arch/arm/include/asm/timex.h:15:24: fatal error: mach/timex.h: No such file or directory
compilation terminated.
/home/luca/android/system/kernel/fp/FP1/kernel/./Kbuild:81: recipe for target 'arch/arm/kernel/asm-offsets.s' failed
make[3]: *** [arch/arm/kernel/asm-offsets.s] Error 1
/home/luca/android/system/kernel/fp/FP1/kernel/Makefile:1007: recipe for target 'prepare0' failed
make[2]: *** [prepare0] Error 2
Makefile:130: recipe for target 'sub-make' failed
make[1]: *** [sub-make] Error 2
```

**Comment by z3ntu** [comment]
`cp mediatek/config/ahong89_wet_jb2/autoconfig/kconfig/project .config`

**Comment by z3ntu** [comment]
`make[2]: *** No rule to make target 'include/config/auto.conf', needed by 'include/config/kernel.release'.  Stop.`

**Comment by z3ntu** [comment]
```
E/dalvikvm( 9760): VM aborting
F/libc    ( 9760): Fatal signal 6 (SIGABRT) at 0x00002620 (code=-6), thread 9760 (zygote)
E/dalvikvm( 9761): JNI posting fatal error: Native registration unable to find class 'com/android/internal/os/RuntimeInit'; aborting...
I/dalvikvm( 9761): "main" prio=5 tid=1 NATIVE
I/dalvikvm( 9761):   | group="main" sCount=0 dsCount=0 obj=0x41d00de0 self=0x41cef3e0
I/dalvikvm( 9761):   | sysTid=9761 nice=0 sched=0/0 cgrp=default handle=1074127188
I/dalvikvm( 9761):   | state=R schedstat=( 247079680 185445009 88 ) utm=18 stm=6 core=0
I/dalvikvm( 9761):   #00  pc 000012f6  /system/lib/libcorkscrew.so (unwind_backtrace_thread+29)
I/dalvikvm( 9761):   #01  pc 00061b7c  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+31)
I/dalvikvm( 9761):   #02  pc 00055b78  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+395)
I/dalvikvm( 9761):   #03  pc 00055be6  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+25)
I/dalvikvm( 9761):   #04  pc 0004a60c  /system/lib/libdvm.so
I/dalvikvm( 9761):   #05  pc 00001fa8  /system/lib/libnativehelper.so (jniRegisterNativeMethods+39)
I/dalvikvm( 9761):   #06  pc 00052562  /system/lib/libandroid_runtime.so
I/dalvikvm( 9761):   #07  pc 00052850  /system/lib/libandroid_runtime.so (android::AndroidRuntime::startReg(_JNIEnv*)+23)
I/dalvikvm( 9761):   #08  pc 000532a0  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, char const*)+183)
I/dalvikvm( 9761):   #09  pc 0000105a  /system/bin/app_process
I/dalvikvm( 9761):   #10  pc 0000e458  /system/lib/libc.so (__libc_init+47)
I/dalvikvm( 9761):   at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm( 9761):   at dalvik.system.NativeStart.main(Native Method)
```

**Comment by z3ntu** [comment]
Logcat log of boot: https://drive.google.com/file/d/0Bzln4ukLNdb0SF9zS0dDZnhtSTA/view?usp=sharing

**Comment by z3ntu** [comment]
Probably because of **libnativehelper**

Flashed boot.img manually via fastboot.

**Comment by z3ntu** [comment]
```
D/AndroidRuntime( 3641): >>>>>> AndroidRuntime START com.android.internal.os.ZygoteInit <<<<<<
D/AndroidRuntime( 3641): CheckJNI is OFF
D/dalvikvm( 3641): Unable to stat classpath element '/system/framework/mediatek-common.jar'
D/dalvikvm( 3641): Unable to stat classpath element '/system/framework/mediatek-framework.jar'
D/dalvikvm( 3641): Unable to stat classpath element '/system/framework/mediatek-op.jar'
D/dalvikvm( 3641): Unable to stat classpath element '/system/framework/secondary-framework.jar'
D/dalvikvm( 3641): Unable to stat classpath element '/system/framework/CustomProperties.jar'
D/dalvikvm( 3641): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 3641): Added shared lib libjavacore.so 0x0
D/dalvikvm( 3641): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 3641): Added shared lib libnativehelper.so 0x0
D/dalvikvm( 3641): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
E/dalvikvm( 3641): JNI posting fatal error: Native registration unable to find class 'com/android/internal/os/RuntimeInit'; aborting...
I/dalvikvm( 3641): "main" prio=5 tid=1 NATIVE
I/dalvikvm( 3641):   | group="main" sCount=0 dsCount=0 obj=0x41556de0 self=0x4148e418
I/dalvikvm( 3641):   | sysTid=3641 nice=0 sched=0/0 cgrp=default handle=1073836372
I/dalvikvm( 3641):   | state=R schedstat=( 252614769 1034538 25 ) utm=17 stm=8 core=1
I/dalvikvm( 3641):   #00  pc 000012f6  /system/lib/libcorkscrew.so (unwind_backtrace_thread+29)
I/dalvikvm( 3641):   #01  pc 00061b7c  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+31)
I/dalvikvm( 3641):   #02  pc 00055b78  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+395)
I/dalvikvm( 3641):   #03  pc 00055be6  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+25)
I/dalvikvm( 3641):   #04  pc 0004a60c  /system/lib/libdvm.so
I/dalvikvm( 3641):   #05  pc 00001fa8  /system/lib/libnativehelper.so (jniRegisterNativeMethods+39)
I/dalvikvm( 3641):   #06  pc 00052562  /system/lib/libandroid_runtime.so
I/dalvikvm( 3641):   #07  pc 00052850  /system/lib/libandroid_runtime.so (android::AndroidRuntime::startReg(_JNIEnv*)+23)
I/dalvikvm( 3641):   #08  pc 000532a0  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, char const*)+183)
I/dalvikvm( 3641):   #09  pc 0000105a  /system/bin/app_process
I/dalvikvm( 3641):   #10  pc 0000e458  /system/lib/libc.so (__libc_init+47)
I/dalvikvm( 3641):   at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm( 3641):   at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm( 3641): 
E/dalvikvm( 3641): VM aborting
F/libc    ( 3641): Fatal signal 6 (SIGABRT) at 0x00000e39 (code=-6), thread 3641 (zygote)
```
